"""Database layer."""

from .coach_repos import GoalRepository, HabitRepository
from .models import (
    Backup,
    Base,
    ChatSession,
    Conversation,
    EmotionEvent,
    Feedback,
    Goal,
    Habit,
    HabitCheck,
    KnowledgeFact,
    Log,
    Memory,
    PushSubscription,
    Repository,
    Session,
    Task,
    User,
    UserInsight,
)
from .repositories import (
    BackupRepository,
    ConversationRepository,
    EmotionRepository,
    FeedbackRepository,
    LogRepository,
    MemoryRepository,
    RepoRepository,
    SessionRepository,
    TaskRepository,
    UserRepository,
)
from .knowledge_repo import KnowledgeRepository
from .session import dispose_db, get_engine, get_sessionmaker, init_db, session_scope

__all__ = [
    "Base",
    "User",
    "Session",
    "Conversation",
    "Task",
    "Log",
    "Backup",
    "Repository",
    "Memory",
    "PushSubscription",
    "EmotionEvent",
    "Feedback",
    "Goal",
    "Habit",
    "HabitCheck",
    "ChatSession",
    "KnowledgeFact",
    "UserInsight",
    "KnowledgeRepository",
    "UserRepository",
    "SessionRepository",
    "ConversationRepository",
    "TaskRepository",
    "LogRepository",
    "BackupRepository",
    "RepoRepository",
    "MemoryRepository",
    "EmotionRepository",
    "FeedbackRepository",
    "GoalRepository",
    "HabitRepository",
    "get_engine",
    "get_sessionmaker",
    "session_scope",
    "init_db",
    "dispose_db",
]
